### PR TITLE
Improvement of readme

### PR DESCRIPTION
**Pull request by manorit2001**
This PR focuses on Improving the readme, 

- [x] Updated the introduction
- [x] Introduced features section 
- [x] Choosing template for the documentation of functions
- [x] Updating all the functions with similar documentation style

### CODE REVIEW

**Comment by manorit2001** [comment]
@Karan-Malik Does the documentation of the 1st function look better with just docstrings or do you have something better in mind?

**Comment by manorit2001** [comment]
The PR is not complete, I have just updated only the 1st function in the readme with the updated template, I am marking it for draft again

**Comment by Karan-Malik** [comment]
> @Karan-Malik Does the documentation of the 1st function look better with just docstrings or do you have something better in mind?

The one with docstring looks better. Thank you!

**Comment by manorit2001** [comment]
> > @Karan-Malik Does the documentation of the 1st function look better with just docstrings or do you have something better in mind?
> 
> The one with docstring looks better. Thank you!

Fine, then I'll update all the functions documentation in same format

**Comment by manorit2001** [comment]
@Karan-Malik I have updated the readme, please check

**Comment by manorit2001** [comment]
I have rebased the branch so that it is ready for merge if everything seems fine

**Comment by Karan-Malik** [comment]
Everything seems good.

**Comment by ashutoshvarma** [comment]
😆 accha time pass kr rahe ho

**Pull request merged**
